name: regressivo_web_poc_prod

on:
  push:
    branches:
      - main  # ajuste de acordo com o nome da sua branch principal

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework Tests
        run: |
          python run_tests.py
        env:
          BROWSER: chrome  # ajuste para o navegador desejado
